My(yang kai)
FireEmblemUniverse/VBA-Blitz-Tendency pull request #76
Opened 2018-07-17 03:51 UTC by YangKaiIsTaken

All my changes:
Custom Definitions.event(for defining Seibah and Rinslet)
Ch19.event
Ch20.event
Master Events Installer
Ch19.tmx
Ch20.tmx
4 mugs

changes also in Chapter Data Editor, Character Editor and Personal Skill Editor.
As well as chapter_names.txt

2018-07-17 04:26 UTC, Crazycolorz5 requested changes

2018-07-17 04:30 UTC, Crazycolorz5 commented
Assembly fails with the errors
```
Errors:
In File Ch19.event, Line 5, Column 1: Unrecognized identifier: ChapterID
In File Ch19.event, Line 5, Column 1: Unrecognized identifier: map_id
In File Ch20.event, Line 5, Column 1: Unrecognized identifier: ChapterID
In File Ch20.event, Line 5, Column 1: Unrecognized identifier: map_id
Errors occurred; no changes written.```
This is due to the missing properties on the maps.

2018-07-17 04:45 UTC, YangKaiIsTaken commented on Events/Ch19.event
> +// Vein(9,23,0x0,DV1Desc) //freeze enemies
It's just leftover from my template event file, that I never remove.(It's not meant to be there)

2018-07-17 04:45 UTC, YangKaiIsTaken commented on Battle Palettes/pal2EA.py
> +#!/usr/bin/python3
Okay

2018-07-17 04:46 UTC, YangKaiIsTaken commented on Events/Ch19.event
> +UNIT 0xA9 Knight 0x66 Level(16, Enemy, True) [2,12] 0x2 0x00 0x0 0x0 [Javelin,DoorKey] NeverMoveAI
I thought it was okay since I picked up a chapter right one another, so ok, I'm changing them.

2018-07-17 04:47 UTC, YangKaiIsTaken commented on Events/Ch19.event
> +TURN 0x0 CallRein1Ch19 [1,6] 0x0
ye, can be removed if it becomes too hard.

2018-07-17 04:47 UTC, YangKaiIsTaken commented on Events/Ch19.event
> +UNIT Eirika 0x2 0x0 Level(15, Ally, True) [14,19] 0x0 0x0 0x0 0x0 [SteelSword,IronSword,Vulnerary] NoAI
:P

2018-07-17 04:47 UTC, YangKaiIsTaken commented on Events/Ch19.event
> +Opening_eventCh19:
Will do it

2018-07-17 04:47 UTC, YangKaiIsTaken commented on Events/Ch20.event
> +Opening_eventCh20:
Will do it

2018-07-17 23:51 UTC, Crazycolorz5 requested changes

2018-07-17 23:51 UTC, Crazycolorz5 commented on Text/Chapter Text/Chapter 19 and 20.txt
> +## KamitoName
Please move all character text out into `Text/character_text.txt`.

2018-07-18 02:01 UTC, Crazycolorz5 commented on Events/Ch20.event
>  ENIF 0x1  //End of the Else
NoFade should be after the ENIF (aka LABEL)

2018-07-18 04:00 UTC, Crazycolorz5 approved these changes

2018-07-18 04:03 UTC, merged